### ISSUE TITLE
关于复现异常的问题

### ISSUE THREAD

**Issue by Lliu666** [YeRen123455/Infrared-Small-Target-Detection#26]
作者你好，最近在复现DNANet在NUDT-SIRST数据集上的结果时，出现了一下的问题：
![image](https://user-images.githubusercontent.com/63533407/199427291-9d6947b6-3f0d-4d45-9be3-0074d6bf76b6.png)
![image](https://user-images.githubusercontent.com/63533407/199428145-279a27f2-34db-4724-b103-40680e30df0f.png)
可以看到，第一次loss出现了骤降，第二次出现了严重的震荡，结果似乎有很大的随机性，请问你知道这是什么原因吗？不固定随机种子，是不是本来就有很大的随机性？
然后我发现作者虽然定义了学习率函数，但是并没有在训练中使用step（），是作者发现恒定的学习率能有更好的训练结果吗？

**Comment by YeRen123455** [comment]
你好，现有SIRST数据集都比较小，一般在千张左右，我们在训练过程中也发现结果有一定的波动。至于学习率不更新的问题，我们确实发现现有条件下，取一个固定的学习率，网络会收敛得更好。其余学习率更新的方案也可以尝试一下，我们并没有做太多尝试。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月02日 15:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 关于复现异常的问题 (Issue #26) |

作者你好，最近在复现DNANet在NUDT-SIRST数据集上的结果时，出现了一下的问题：


可以看到，第一次loss出现了骤降，第二次出现了严重的震荡，结果似乎有很大的随机性，请问你知道这是什么原因吗？不固定随机种子，是不是本来就有很大的随机性？
然后我发现作者虽然定义了学习率函数，但是并没有在训练中使用step（），是作者发现恒定的学习率能有更好的训练结果吗？

**Comment by Lliu666** [comment]
请问你觉得固定学习率下，loss出现骤降的原因是什么？只是单纯的偶然事件吗？我是为了验证偶然性进行了第二次实验，但可以看到结果很不理想，实验条件是epoch=1500，lr=0.05

**Comment by 1071189147** [comment]
> 作者你好，最近在复现DNANet在NUDT-SIRST数据集上的结果时，出现了一下的问题： ![image](https://user-images.githubusercontent.com/63533407/199427291-9d6947b6-3f0d-4d45-9be3-0074d6bf76b6.png) ![image](https://user-images.githubusercontent.com/63533407/199428145-279a27f2-34db-4724-b103-40680e30df0f.png) 可以看到，第一次loss出现了骤降，第二次出现了严重的震荡，结果似乎有很大的随机性，请问你知道这是什么原因吗？不固定随机种子，是不是本来就有很大的随机性？ 然后我发现作者虽然定义了学习率函数，但是并没有在训练中使用step（），是作者发现恒定的学习率能有更好的训练结果吗？


我也出现这样的问题，多次训练，IoU最高是0.85几，难以达到0.89的程度

**Comment by YeRen123455** [comment]
你好，0.89的IoU是在中科大云服务器上取得的最高值，因此我们并没有在论文中体现，仅放出模型参数供大家参考。0.86左右的IoU是可以多次获得的，建议您采用固定的学习率，deep supervision =True，然后再重复训练几次。

**Comment by 2021BUPTer** [comment]
您好！我想请问这个图是在哪里绘制的？

**Comment by 2021BUPTer** [comment]
> 作者你好，最近在复现DNANet在NUDT-SIRST数据集上的结果时，出现了一下的问题： ![image](https://user-images.githubusercontent.com/63533407/199427291-9d6947b6-3f0d-4d45-9be3-0074d6bf76b6.png) ![image](https://user-images.githubusercontent.com/63533407/199428145-279a27f2-34db-4724-b103-40680e30df0f.png) 可以看到，第一次loss出现了骤降，第二次出现了严重的震荡，结果似乎有很大的随机性，请问你知道这是什么原因吗？不固定随机种子，是不是本来就有很大的随机性？ 然后我发现作者虽然定义了学习率函数，但是并没有在训练中使用step（），是作者发现恒定的学习率能有更好的训练结果吗？

？

您好，请问您这个图是用什么绘制的呢？我的邮箱yifang_guo@126.com

**Comment by 1071189147** [comment]
> > 作者你好，最近在复现DNANet在NUDT-SIRST数据集上的结果时，出现了一下的问题： ![image](https://user-images.githubusercontent.com/63533407/199427291-9d6947b6-3f0d-4d45-9be3-0074d6bf76b6.png) ![image](https://user-images.githubusercontent.com/63533407/199428145-279a27f2-34db-4724-b103-40680e30df0f.png) 可以看到，第一次loss出现了骤降，第二次出现了严重的震荡，结果似乎有很大的随机性，请问你知道这是什么原因吗？不固定随机种子，是不是本来就有很大的随机性？ 然后我发现作者虽然定义了学习率函数，但是并没有在训练中使用step（），是作者发现恒定的学习率能有更好的训练结果吗？
> 
> ？
> 
> 您好，请问您这个图是用什么绘制的呢？我的邮箱[yifang_guo@126.com](mailto:yifang_guo@126.com)

应该是tensorboard自带的，

**Comment by ghost-baigao** [comment]
作者你好，本人小白，我复现DNANet网络时，在linux系统上用指令运行train.py文件，出现了报错，需要这么解决这个问题呢Traceback (most recent call last):
  File "/home/LYH/Infrared-Small-Target-Detection/train.py", line 132, in <module>
    main(args)
  File "/home/LYH/Infrared-Small-Target-Detection/train.py", line 124, in main
    trainer = Trainer(args)
  File "/home/LYH/Infrared-Small-Target-Detection/train.py", line 47, in __init__
    model           = model.cuda()
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by lkyu-ly** [comment]
> 作者你好，本人小白，我复现DNANet网络时，在linux系统上用指令运行train.py文件，出现了报错，需要这么解决这个问题呢Traceback (most recent call last): File "/home/LYH/Infrared-Small-Target-Detection/train.py", line 132, in 文件 "/home/LYH/Infrared-Small-Target-Detection/train.py"，第 132 行， main(args) File "/home/LYH/Infrared-Small-Target-Detection/train.py", line 124, in main文件 "/home/LYH/Infrared-Small-Target-Detection/train.py"，第 124 行，在 main 中 trainer = Trainer(args) File "/home/LYH/Infrared-Small-Target-Detection/train.py", line 47, in **init**文件 "/home/LYH/Infrared-Small-Target-Detection/train.py"，第 47 行，在初始化时 model = model.cuda() UnboundLocalError: local variable 'model' referenced before assignment局部变量 'model' 在赋值前被引用

https://github.com/YeRen123455/Infrared-Small-Target-Detection/blob/21584be00d19bc3080c78deee0953af250bed99b/train.py#L43-L50

问一下你模型传递的参数是什么：问题可能出在这里。model若非预定义的`DNANET`就会跳过44行的`model`赋值，导致47行变量没赋值就引用了。

---

下面贴ai建议：

对于出现的`UnboundLocalError: local variable 'model' referenced before assignment`错误，原因是您的`--model`参数传递的是`DNANet-ResNet-18`，但代码中只有`args.model == "DNANet"`的条件分支会初始化模型。其他模型名未处理导致`model`变量未被定义。

**修复步骤：**

1. **修改模型初始化条件**
   将判断条件改为允许匹配带有ResNet后缀的模型名：

   ```python
   # 原代码
   if args.model == "DNANet":
       model = DNANet(...)

   # 修改后
   if args.model.startswith("DNANet"):  # 支持DNANet及其变种（如DNANet-ResNet-18）
       model = DNANet(
           num_classes=1,
           input_channels=args.in_channels,
           block=Res_CBAM_block,
           num_blocks=num_blocks,
           nb_filter=nb_filter,
           deep_supervision=args.deep_supervision
       )
   ```

2. **确保其他模型分支的处理（如有）**
   如果还有其他模型类型，需要补充对应的初始化分支。

3. **运行命令调整（可选）**
   检查是否本意是使用`DNANet`作为主模型，通过`--backbone resnet_18`指定结构。此时应简化命令：
   ```bash
   python train.py [...] --model DNANet --backbone resnet_18 [...]
   ```

**代码修改示例：**
在`train.py`中找到模型初始化部分，并调整为：

```python
# 原条件检查只针对纯"DNANet"字符串
# 调整后兼容以DNANet开头的模型名（如DNANet-ResNet-18）
if args.model.startswith("DNANet"):
    model = DNANet(
        num_classes=1,
        input_channels=args.in_channels,
        block=Res_CBAM_block,
        num_blocks=num_blocks,
        nb_filter=nb_filter,
        deep_supervision=args.deep_supervision
    )
```

此修改确保当模型名称以`DNANet`开头时正确初始化，解决变量未定义问题。
